Config:
    # service type value in essential, file and metadata
    service-type: synonym_puller
     # db server
    server: localhost 
    # # db port
    port: 27017
    # # db user id
    user: test
    # # db user password
    pwd: test1234
    # db name
    db: crdc-datahub
    synonym-api-url: https://api.github.com/repos/CBIIT/crdc-datahub-terms/contents