Config:
    # service type value in essential, file and metadata
    service-type: file
    # MongoDB configurations
    # connection string
    connection-str: mongodb://xxx:xxx@localhost:27017/?authMechanism=DEFAULT
    db: crdc-datahub
    #sqs configuration
    sqs: crdcdh-queue-pgu.fifo
    s3_bucket_drive: /s3_bucket
   