Config:
Config:
    # MongoDB configurations
    # connection string
    connection-str: mongodb://xxx:xxx@localhost:27017/?authMechanism=DEFAULT
    batch-db: crdc-datahub
    matadata-db: data-commons
    #sqs configuration
    sqs: crdcdh-queue-pgu.fifo
    models-dir:  https://github.com/CBIIT/crdc-datahub-models 

   