name: Build Authn service
permissions: 
  contents: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      environment:
        description: env to build
        type: environment
#      code_branch:
#        description: branch to build
#        required: false
#        default: main
      trivy_test_scan:
        description: "Run Trivy Test Scan"
        required: true
        type: boolean
        default: false


jobs:
  build:
    name: Build authn image
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ECR_REPO: "crdc-hub-authn"
      SERVICE: "authn"
      REGION: "us-east-1"
#      CODE_BRANCH: "${{ github.event.inputs.code_branch }}"
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          submodules: true

      - name: Extract branch name
        id: extract_branch
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "branch=$BRANCH_NAME" >> "$GITHUB_ENV"
          echo "Current branch is: $BRANCH_NAME"
#          echo "branch=${{ github.ref_name }}" >> "$GITHUB_ENV"

#      - name: List All Branches
#        run: |
#          git fetch --all
#          git branch -r


      - name: Build Docker Image
        id: build-image
        env:
          REGISTRY_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          IMAGE_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.branch }}.${{ github.run_number }}
        run: |
          echo "Building: $IMAGE_NAME"
          docker build --no-cache -t $IMAGE_NAME -f apps/authn/Dockerfile .

      - name: Run Trivy test scan
        id: trivy-scan
        if: github.event.inputs.trivy_test_scan == 'true'
        env:
          REGISTRY_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          IMAGE_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.branch }}.${{ github.run_number }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_NAME }}'
          format: 'table'
          exit-code: 1
          severity: 'CRITICAL,HIGH'
   
      - name: Configure AWS Role to assume using OIDC authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: login-ecr
        env:
          REGISTRY_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        run:  |
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REGISTRY_URL
 

      - name: Push Docker images
        id: push-image
        if: success()
        env:
          REGISTRY_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.REGION }}.amazonaws.com
          IMAGE_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.branch }}.${{ github.run_number }}
        run: |
          echo "Pushing: $IMAGE_NAME"
          docker push $IMAGE_NAME
